/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:33f2f101-34b0-4fb4-ba04-677996c715d1",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_duS0k51dF",
    "aws_user_pools_web_client_id": "1aj8k5fa5anug6u13hijb59077",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://le3vy73k4bgmtmogo4uqkgi7mq.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile