/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:cd3e3764-c787-47f6-8cf2-1cc42c08b454",
    "aws_cognito_region":"ap-northeast-1",
    "aws_user_pools_id":"ap-northeast-1_5sY9bnjie",
    "aws_user_pools_web_client_id":"2r9s65jnu701pioim7td7ag2uk",
    "oauth": {
        "domain": "botui-production.auth.ap-northeast-1.amazoncognito.com",
        "scope": ["phone", "email", "openid", "profile", "aws.cognito.signin.user.admin"],
        "redirectSignIn":"http://localhost:3001/,https://dev.chachat.survaq.com/admin/,https://www.chachat.survaq.com/admin/",
        "redirectSignOut":"http://localhost:3001/,https://dev.chachat.survaq.com/admin/,https://www.chachat.survaq.com/admin/",
        "responseType": "code"
    },
    "federationTarget":"COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_appsync_graphqlEndpoint":"https://3zi2piv6qrevxdn5nr5yrha7ba.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region":"ap-northeast-1",
    "aws_appsync_authenticationType":"AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "notify",
            "endpoint":"https://c6xqznw338.execute-api.ap-northeast-1.amazonaws.com/production",
            "region": "ap-northeast-1"
        }
    ],
    "aws_user_files_s3_bucket":"botui185011-production",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile