name: Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: npx nx run backend:build:lambda
    - uses: serverless/github-action@master
      with:
        args: deploy --stage=production
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_EXPORTS: ${{ secrets.AWS_EXPORTS_PROD }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        GRAPHQL_API_KEY: ${{ secrets.GRAPHQL_API_KEY_PROD }}